app:
  #------------------------------------------------------------------------------------------------------------------------
  # database address
  #------------------------------------------------------------------------------------------------------------------------
  database:
    host: localhost
    port:
    schema: heaplib
    user: heaplib
    password: heaplib
    url: jdbc:mysql://${app.database.host}:${app.database.port}/${app.database.schema}?useUnicode=yes&characterEncoding=UTF-8&allowLoadLocalInfile=true

  #------------------------------------------------------------------------------------------------------------------------
  # input files path
  #------------------------------------------------------------------------------------------------------------------------
  inputFilesFolder: "."



#------------------------------------------------------------------------------------------------------------------------
# total spring configuration
#------------------------------------------------------------------------------------------------------------------------
spring:
  profiles:
    active: [ "local", "bundle" ]
  
  main:
    banner-mode: off
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  messages:
    use-code-as-default-message: true
    basename: l10n/messages
    fallback-to-system-locale: false
  
  #------------------------------------------------------------------------------------------------------------------------
  # spring configuration of database
  #------------------------------------------------------------------------------------------------------------------------
  datasource:
    url: ${app.database.url}
    username: ${app.database.user}
    password: ${app.database.password}


#------------------------------------------------------------------------------------------------------------------------
# servlet options
#------------------------------------------------------------------------------------------------------------------------
server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always
    include-message: always
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    jsp:
      init-parameters:
        development: false
        ## compiled jsp folder
        #scratchdir: ${java.io.tmpdir}/sb2 
    session:
      timeout: 24h
